import "./globals.css"
import type { Metadata } from "next"
import { Provider } from "react-redux"
import { ThemeProvider } from "@/hooks/ThemeContext"
// import { store } from "@/store";
import StoreProvider from "@/store/storeProvider"

import Navbar from "@/components/Navbar/Navbar"
import Footer from "@/components/Footer"

export const metadata: Metadata = {
  title: "Airport Weather",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html
      lang="en"
      className="scroll-smooth"
      style={{ scrollBehavior: "smooth" }}
    >
      <body>
        <ThemeProvider>
          <div className="font-Rubik flex flex-col min-h-screen justify-between">
            <div className="h-15">
              <Navbar />
            </div>
            <StoreProvider>
              <div className="">{children}</div>
            </StoreProvider>
            <div className="mt-auto">
              <Footer />
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  )
}
